import { Suspense } from "react";
import SiteHeader from "@/components/common/site-header";
import Hero from "./_components/hero";
import Footer from "./_components/footer";
import Screenings from "./_components/screenings";
import ScreeningsLoader from "./_components/screenings/loader";
import Genres from "./_components/genres";
import Cinemas from "./_components/cinemas";
import Blog from "./_components/blog";
import About from "./_components/about";
import { getRandomScreening } from "@/lib/screenings";
import { getGenres } from "@/lib/genres";

// The homepage is static (ISR): no searchParams or cookies are read on the
// server, so the HTML shell (hero = LCP) is served from cache instead of
// being re-rendered per request. Filtered views (?city=, ?genres=, ...) are
// resolved client-side by the Screenings section via /api/screenings, and
// the middleware already marks any query-string variant of "/" with
// X-Robots-Tag: noindex, follow.
export const revalidate = 300;

const HomePage = async () => {
  const [randomScreening, genres] = await Promise.all([
    getRandomScreening().catch(() => null),
    getGenres().catch(() => []),
  ]);

  // Blur placeholders come precomputed from the API (generated by the
  // scraper), so the hero never flashes a black frame while the backdrop
  // streams in.
  const backdropBlurDataUrl = randomScreening?.movie.backdropBlurDataUrl ?? null;
  const posterBlurDataUrl = randomScreening?.movie.posterBlurDataUrl ?? null;

  return (
    <>
      {/* Hidden at the top (the hero carries its own nav), revealed as a
          floating glass bar while scrolling back up. */}
      <SiteHeader overlay />
      <Hero
        screening={randomScreening}
        backdropBlurDataUrl={backdropBlurDataUrl}
        posterBlurDataUrl={posterBlurDataUrl}
      />
      {/* Suspense boundary: Screenings reads useSearchParams, which opts
          the client tree below this boundary out of static prerendering. */}
      <Suspense fallback={<ScreeningsLoader />}>
        <Screenings genres={genres} />
      </Suspense>
      <Genres />
      <Cinemas />
      <Blog />
      <About />
      <Footer />
    </>
  );
};

export default HomePage;
