import { Suspense } from "react";
import SiteHeader from "@/components/common/site-header";
import Hero from "./_components/hero";
import Footer from "./_components/footer";
import Screenings from "./_components/screenings";
import ScreeningsLoader from "./_components/screenings/loader";
import Genres from "./_components/genres";
import Cinemas from "./_components/cinemas";
import Blog from "./_components/blog";
import About from "./_components/about";
import { getFeaturedHeroScreening, fetchHomeScreenings } from "@/lib/screenings";
import { getGenres } from "@/lib/genres";

// The homepage is static (ISR): no searchParams or cookies are read on the
// server, so the HTML shell (hero = LCP) is served from cache instead of
// being re-rendered per request. The default screenings grid is rendered
// straight into that cached HTML; only filtered views (?city=, ?genres=,
// ...) and the stored preferred city are resolved client-side by the
// Screenings section via /api/screenings, and the middleware already marks
// any query-string variant of "/" with X-Robots-Tag: noindex, follow.
export const revalidate = 300;

const HomePage = async () => {
  const [heroScreening, genres, homeScreenings] = await Promise.all([
    getFeaturedHeroScreening().catch(() => null),
    getGenres().catch(() => []),
    fetchHomeScreenings().catch(() => ({ screenings: [], hasMore: false })),
  ]);

  // Blur placeholders come precomputed from the API (generated by the
  // scraper), so the hero never flashes a black frame while the backdrop
  // streams in.
  const backdropBlurDataUrl = heroScreening?.movie.backdropBlurDataUrl ?? null;
  const posterBlurDataUrl = heroScreening?.movie.posterBlurDataUrl ?? null;

  return (
    <>
      {/* Hidden at the top (the hero carries its own nav), revealed as a
          floating glass bar while scrolling back up. */}
      <SiteHeader overlay />
      <Hero
        screening={heroScreening}
        backdropBlurDataUrl={backdropBlurDataUrl}
        posterBlurDataUrl={posterBlurDataUrl}
      />
      {/* Suspense boundary: Screenings reads useSearchParams, which opts
          the client tree below this boundary out of static prerendering.
          The default screenings are server-rendered here so the grid is in
          the cached HTML; the client only refetches for active filters or
          the stored preferred city. */}
      <Suspense fallback={<ScreeningsLoader />}>
        <Screenings
          genres={genres}
          initialScreenings={homeScreenings.screenings}
          initialHasMore={homeScreenings.hasMore}
        />
      </Suspense>
      {/* Each below-the-fold section streams on its own so a slow data fetch
          (e.g. the cinemas list) never blocks the hero shell or the others.
          The page is statically prerendered, so crawlers still get the fully
          baked HTML; the boundaries only matter on dev/revalidation renders. */}
      <Suspense fallback={null}>
        <Genres />
      </Suspense>
      <Suspense fallback={null}>
        <Cinemas />
      </Suspense>
      <Suspense fallback={null}>
        <Blog />
      </Suspense>
      <About />
      <Footer />
    </>
  );
};

export default HomePage;
