export interface IGenre {
  id: number;
  slug: string;
  name: string;
  description: string | null;
  updatedAt?: string | null;
}

export interface IMoviePerson {
  id?: number;
  sourceId?: number;
  /** Director slug for linking to /rezyserzy/[slug]; absent for cast/crew. */
  slug?: string;
  name: string;
  url?: string;
}

export interface IMovieCountry {
  id?: number;
  name: string;
  countryCode?: string;
}

export interface IMovieSummary {
  id: number;
  slug: string;
  title: string;
  titleOriginal: string | null;
  productionYear: number;
  duration: number | null;
  posterUrl: string | null;
  genres: IGenre[];
  updatedAt?: string | null;
}

export interface IMovieHero extends IMovieSummary {
  description: string | null;
  backdropUrl: string | null;
  /** Tiny base64 webp previews generated by the scraper; rendered as
   * next/image placeholder="blur" without any frontend processing. */
  posterBlurDataUrl?: string | null;
  backdropBlurDataUrl?: string | null;
  videoUrl: string | null;
  /** Sent only by endpoints that load the directors relation
   * (e.g. /screenings/random-screening for the home hero). */
  directors?: IMoviePerson[] | null;
}

export interface IMovieRatingScore {
  score: number;
  votes: number;
}

export interface IMovieRatings {
  users: IMovieRatingScore | null;
  critics: IMovieRatingScore | null;
}

export interface IMovie {
  id: number;
  slug: string;
  title: string;
  titleOriginal: string | null;
  description: string | null;
  productionYear: number;
  duration: number | null;
  language: string | null;
  posterUrl: string | null;
  backdropUrl: string | null;
  /** Tiny base64 webp previews generated by the scraper; rendered as
   * next/image placeholder="blur" without any frontend processing. */
  posterBlurDataUrl?: string | null;
  backdropBlurDataUrl?: string | null;
  videoUrl: string | null;
  worldPremiereDate: string | null;
  polishPremiereDate: string | null;
  directors?: IMoviePerson[] | null;
  actors?: IMoviePerson[] | null;
  countries?: IMovieCountry[] | null;
  scriptwriters?: IMoviePerson[] | null;
  countryOfOrigin?: IMovieCountry[] | null;
  screenwriters?: IMoviePerson[] | null;
  genres: IGenre[];
  sourceUrl?: string | null;
  ratings?: IMovieRatings | null;
  filmwebUrl?: string | null;
}

export interface IMultiCityMovie {
  id: number;
  slug: string;
  title: string;
  productionYear: number;
  posterUrl: string | null;
  citiesCount: number;
  description: string | null;
  duration: number | null;
}

export interface PaginatedResponse<T> {
  data: readonly T[];
  meta: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
  };
}
